name: flutter_quran
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: hafs
      fonts:
        - asset: assets/fonts/hafs/UthmanicHafs1-Ver13.otf
    - family: dubai
      fonts:
        - asset: assets/fonts/dubai/Dubai-Light.ttf
          weight: 300
        - asset: assets/fonts/dubai/Dubai-Regular.ttf
          weight: 400
        - asset: assets/fonts/dubai/Dubai-Medium.ttf
          weight: 500
        - asset: assets/fonts/dubai/Dubai-Bold.ttf
          weight: 700
